# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Codesigning and uploading to Testfligt"
  lane :beta do
    sync_code_signing(type: "appstore")
    build_app(scheme: "Fitness Tracker")
    upload_to_testflight
  end
end
